name: CI/CD Pipeline

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install root dependencies
      run: npm install
      
    - name: Build app
      run: npm run build 

    - name: Install cdktf
      run: |
       cd cdk
       npm install @arc-iac/tf-cdk-spa 

    - name: Generate CDK .env file
      run: |
        echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> cdk/.env
        echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}" >> cdk/.env
        echo "CUSTOM_DOMAIN=${{ secrets.CUSTOM_DOMAIN }}" >> cdk/.env
        echo "HOSTED_ZONE_ID=${{ secrets.HOSTED_ZONE_ID }}" >> cdk/.env
        echo "RELATIVE_PATH_TO_BUILD_DIR=../build" >> cdk/.env

    - name: CDK Deploy
      run: |
       cd cdk
       npx cdktf deploy test-s3 --auto-approve
